version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/tellalife
    ports:
      - 3000:3000
    image: app:tellalife
    container_name: tellalife_container
    command:  npm start

    # npm run build&&yarn global add serve&&serve -s build