version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/tellalife
    ports:
      - 5000:5000
    image: app:tellalife
    container_name: tellalife_container
    command:  npm start
